apiVersion: v1
kind: Pod
metadata:
  name: earthquake-system
spec:
  containers:

    # -----------------------------
    # 1) QDRANT VECTOR DATABASE
    # -----------------------------
    - name: qdrant
      image: qdrant/qdrant:latest
      ports:
        - containerPort: 6333
          hostPort: 6333
        - containerPort: 6334
          hostPort: 6334

      env:
        - name: QDRANT_API_KEY
          value: "admin-key"
      volumeMounts:
        - mountPath: /qdrant/storage
          name: qdrant-storage

    # -----------------------------
    # 2) EARTHQUAKE MULTI-AGENT PIPELINE
    # -----------------------------
    - name: earthquake-app
      image: localhost/earthquake-agent:latest
      command:
        - "python"
        - "main.py"
        - "/app/data"
      env:
        - name: QDRANT_URL
          value: "http://localhost:6333"
        - name: QDRANT_API_KEY
          value: "admin-key"
        - name: QDRANT_COLLECTION
          value: "earthquake_events"
        - name: EMBEDDING_DIM
          value: "384"          


      volumeMounts:
        - mountPath: /app/data
          name: data-volume

    # -----------------------------
    # 3) STREAMLIT UI
    # -----------------------------
    - name: streamlit-ui
      image: localhost/earthquake-agent:latest
      command:
        - "streamlit"
        - "run"
        - "app.py"
        - "--server.port=8501"
        - "--server.address=0.0.0.0"
      ports:
        - containerPort: 8501
          hostPort: 8501

      env:
        - name: QDRANT_URL
          value: "http://localhost:6333"
        - name: EMBEDDING_DIM
          value: "384"
        - name: COHERE_API_KEY
          value: ---ADD key---      
      volumeMounts:
        - mountPath: /app/data
          name: data-volume

  volumes:
    - name: qdrant-storage
      hostPath:
        path: /mnt/c/Multi-agent-Terremoti/qdrant_storage
        type: DirectoryOrCreate

    - name: data-volume
      hostPath:
        path: /mnt/c/Multi-agent-Terremoti/data
        type: Directory